# Railway v2 config - Force Docker build
[[services]]
name = "signaling"

[services.signaling.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.signaling.deploy]
restartPolicyType = "on-failure"

[services.signaling.variables]
PORT = "3000"
RUST_LOG = "info"