# Deploy only the Rust signaling server to Railway
# STUN server requires UDP ports which Railway doesn't support well
# Use external STUN servers instead

[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on-failure"

[variables]
PORT = "3000" 
RUST_LOG = "info"